import type { ReviewItem, SkillArea } from "./types";

export const vocabularyCards = [
  { word: "appointment", meaning: "预约，约定", example: "I have a dentist appointment this afternoon.", prompt: "我今天下午有一个牙医预约。" },
  { word: "recommend", meaning: "推荐", example: "Can you recommend a good restaurant nearby?", prompt: "你能推荐附近一家好餐厅吗？" },
  { word: "available", meaning: "有空的，可用的", example: "Are you available after work?", prompt: "你下班后有空吗？" },
  { word: "comfortable", meaning: "舒服的，自在的", example: "I feel comfortable speaking English with you.", prompt: "和你说英语我觉得很自在。" },
  { word: "actually", meaning: "其实，实际上", example: "Actually, I prefer tea to coffee.", prompt: "其实，比起咖啡我更喜欢茶。" },
  { word: "probably", meaning: "很可能，大概", example: "I will probably stay at home tonight.", prompt: "我今晚可能会待在家里。" },
  { word: "usually", meaning: "通常", example: "I usually take a walk after dinner.", prompt: "我通常晚饭后散步。" },
  { word: "prefer", meaning: "更喜欢", example: "I prefer simple English sentences.", prompt: "我更喜欢简单的英文句子。" },
  { word: "improve", meaning: "提高，改善", example: "I want to improve my speaking skills.", prompt: "我想提高我的口语能力。" },
  { word: "practice", meaning: "练习", example: "I practice English for twenty minutes every day.", prompt: "我每天练习英语20分钟。" },
  { word: "confident", meaning: "自信的", example: "I feel more confident when I speak slowly.", prompt: "当我慢慢说时，我更自信。" },
  { word: "explain", meaning: "解释", example: "Could you explain this word again?", prompt: "你能再解释一下这个单词吗？" },
  { word: "understand", meaning: "理解", example: "I understand the main idea.", prompt: "我理解主要意思。" },
  { word: "remember", meaning: "记得，记住", example: "I remember this phrase because I use it often.", prompt: "我记得这个短语，因为我经常用它。" },
  { word: "forget", meaning: "忘记", example: "I sometimes forget new words.", prompt: "我有时候会忘记新单词。" },
  { word: "prepare", meaning: "准备", example: "I need to prepare for tomorrow's meeting.", prompt: "我需要为明天的会议做准备。" },
  { word: "important", meaning: "重要的", example: "Daily practice is important for learning English.", prompt: "每日练习对学习英语很重要。" },
  { word: "interesting", meaning: "有趣的", example: "This topic is interesting to me.", prompt: "这个话题对我来说很有趣。" },
  { word: "busy", meaning: "忙的", example: "I am busy today, but I can study for twenty minutes.", prompt: "我今天很忙，但我可以学习20分钟。" },
  { word: "relax", meaning: "放松", example: "I like to relax after work.", prompt: "我喜欢下班后放松。" },
];

export const writingLessons = [
  {
    grammar: "want to + 动词原形",
    tip: "表达“想要做某事”时，用 want to + 动词原形。不要写 want improve，要写 want to improve。",
    examples: ["I want to improve my spoken English.", "I want to practice English every day."],
    prompts: [
      { zh: "我想提高我的英语口语。", answer: "I want to improve my spoken English." },
      { zh: "我想每天练习英语。", answer: "I want to practice English every day." },
      { zh: "我想学习更多日常单词。", answer: "I want to learn more daily words." },
      { zh: "我想说得更自然。", answer: "I want to speak more naturally." },
      { zh: "我想用英语和朋友聊天。", answer: "I want to chat with friends in English." },
    ],
  },
];

export const writingPrompts = writingLessons[0].prompts.map((prompt) => ({
  grammar: writingLessons[0].grammar,
  tip: writingLessons[0].tip,
  ...prompt,
}));

export const dailyThemes = [
  {
    id: "daily-routine",
    title: "日常生活：安排一天",
    domain: "生活",
    description: "学会描述日常安排、时间、习惯和简单偏好。",
    vocabulary: vocabularyCards,
    speaking: {
      title: "聊聊你的一天",
      opener: "Today we will talk about your daily routine. What do you usually do in the morning?",
      goal: "用英文描述一天中的安排，并补充一个原因或细节。",
    },
    writingLesson: writingLessons[0],
  },
  {
    id: "work-communication",
    title: "职场沟通：会议和协作",
    domain: "职场",
    description: "练习会议、时间安排、任务沟通和礼貌请求。",
    vocabulary: [
      { word: "meeting", meaning: "会议", example: "I have a meeting at ten.", prompt: "我十点有一个会议。" },
      { word: "schedule", meaning: "日程，安排", example: "My schedule is full today.", prompt: "我今天的日程很满。" },
      { word: "deadline", meaning: "截止日期", example: "The deadline is this Friday.", prompt: "截止日期是这个星期五。" },
      { word: "project", meaning: "项目", example: "This project is important.", prompt: "这个项目很重要。" },
      { word: "update", meaning: "更新，进展", example: "Can you give me a quick update?", prompt: "你能给我一个简短进展吗？" },
      { word: "task", meaning: "任务", example: "I finished this task yesterday.", prompt: "我昨天完成了这个任务。" },
      { word: "team", meaning: "团队", example: "Our team works well together.", prompt: "我们的团队合作很好。" },
      { word: "confirm", meaning: "确认", example: "Please confirm the time.", prompt: "请确认时间。" },
      { word: "discuss", meaning: "讨论", example: "Let's discuss this tomorrow.", prompt: "我们明天讨论这个吧。" },
      { word: "prepare", meaning: "准备", example: "I need to prepare the report.", prompt: "我需要准备报告。" },
      { word: "report", meaning: "报告", example: "I sent the report this morning.", prompt: "我今天早上发了报告。" },
      { word: "client", meaning: "客户", example: "The client asked a question.", prompt: "客户问了一个问题。" },
      { word: "agree", meaning: "同意", example: "I agree with your idea.", prompt: "我同意你的想法。" },
      { word: "suggest", meaning: "建议", example: "I suggest a short meeting.", prompt: "我建议开一个短会。" },
      { word: "available", meaning: "有空的", example: "Are you available at three?", prompt: "你三点有空吗？" },
      { word: "urgent", meaning: "紧急的", example: "This task is urgent.", prompt: "这个任务很紧急。" },
      { word: "follow up", meaning: "跟进", example: "I will follow up tomorrow.", prompt: "我明天会跟进。" },
      { word: "share", meaning: "分享", example: "Could you share the file?", prompt: "你能分享这个文件吗？" },
      { word: "clear", meaning: "清楚的", example: "Your explanation is clear.", prompt: "你的解释很清楚。" },
      { word: "issue", meaning: "问题", example: "We found one small issue.", prompt: "我们发现了一个小问题。" },
    ],
    speaking: {
      title: "安排一次会议",
      opener: "Let's practice a work conversation. Are you available for a short meeting today?",
      goal: "用英文确认时间、说明安排，并礼貌回应。",
    },
    writingLesson: {
      grammar: "Could you...? 礼貌请求",
      tip: "职场沟通里常用 Could you...? 表达礼貌请求。句型是 Could you + 动词原形...?",
      examples: ["Could you send me the report?", "Could you confirm the meeting time?"],
      prompts: [
        { zh: "你能把报告发给我吗？", answer: "Could you send me the report?" },
        { zh: "你能确认会议时间吗？", answer: "Could you confirm the meeting time?" },
        { zh: "你能分享这个文件吗？", answer: "Could you share the file?" },
        { zh: "你能给我一个简短更新吗？", answer: "Could you give me a quick update?" },
        { zh: "你能明天跟进这个问题吗？", answer: "Could you follow up on this issue tomorrow?" },
      ],
    },
  },
  {
    id: "learning-growth",
    title: "学习成长：英语进步",
    domain: "学习",
    description: "围绕学习计划、练习方法、困难和进步表达自己。",
    vocabulary: [
      { word: "goal", meaning: "目标", example: "My goal is to speak clearly.", prompt: "我的目标是说得清楚。" },
      { word: "habit", meaning: "习惯", example: "Daily practice is a good habit.", prompt: "每日练习是一个好习惯。" },
      { word: "review", meaning: "复习", example: "I review new words at night.", prompt: "我晚上复习新单词。" },
      { word: "mistake", meaning: "错误", example: "Mistakes help me learn.", prompt: "错误帮助我学习。" },
      { word: "progress", meaning: "进步", example: "I can see my progress.", prompt: "我能看到我的进步。" },
      { word: "practice", meaning: "练习", example: "Practice makes speaking easier.", prompt: "练习让口语更容易。" },
      { word: "improve", meaning: "提高", example: "I want to improve my writing.", prompt: "我想提高我的写作。" },
      { word: "remember", meaning: "记住", example: "I remember words better with examples.", prompt: "通过例句我更容易记住单词。" },
      { word: "forget", meaning: "忘记", example: "I sometimes forget grammar rules.", prompt: "我有时会忘记语法规则。" },
      { word: "repeat", meaning: "重复", example: "Please repeat the sentence.", prompt: "请重复这个句子。" },
      { word: "explain", meaning: "解释", example: "Can you explain it simply?", prompt: "你能简单解释一下吗？" },
      { word: "example", meaning: "例子", example: "This example is useful.", prompt: "这个例子很有用。" },
      { word: "sentence", meaning: "句子", example: "Write one complete sentence.", prompt: "写一个完整句子。" },
      { word: "grammar", meaning: "语法", example: "This grammar point is useful.", prompt: "这个语法点很有用。" },
      { word: "fluently", meaning: "流利地", example: "I want to speak more fluently.", prompt: "我想说得更流利。" },
      { word: "clearly", meaning: "清楚地", example: "Please speak clearly.", prompt: "请说清楚一点。" },
      { word: "confident", meaning: "自信的", example: "I feel more confident now.", prompt: "我现在更自信了。" },
      { word: "method", meaning: "方法", example: "This method works for me.", prompt: "这个方法适合我。" },
      { word: "focus", meaning: "专注", example: "I focus on useful phrases.", prompt: "我专注于有用短语。" },
      { word: "challenge", meaning: "挑战", example: "Speaking is a challenge for me.", prompt: "口语对我是一个挑战。" },
    ],
    speaking: {
      title: "谈谈学习目标",
      opener: "Today's topic is learning English. What is your English learning goal?",
      goal: "用英文说明学习目标、困难和下一步计划。",
    },
    writingLesson: {
      grammar: "because 表达原因",
      tip: "because 用来解释原因。可以把简单句变得更完整：I practice every day because I want to improve.",
      examples: ["I review words because I forget them easily.", "I practice speaking because I want to be more confident."],
      prompts: [
        { zh: "我每天复习，因为我容易忘记单词。", answer: "I review every day because I forget words easily." },
        { zh: "我练习口语，因为我想更自信。", answer: "I practice speaking because I want to be more confident." },
        { zh: "我喜欢例句，因为它们容易记住。", answer: "I like examples because they are easy to remember." },
        { zh: "我慢慢说，因为我想说得更清楚。", answer: "I speak slowly because I want to speak more clearly." },
        { zh: "我每天学习，因为小步骤更容易坚持。", answer: "I study every day because small steps are easier to keep." },
      ],
    },
  },
  {
    id: "health-wellness",
    title: "健康生活：身心平衡",
    domain: "健康",
    description: "学习描述身体状态、生活习惯和保持健康的日常表达。",
    vocabulary: [
      { word: "healthy", meaning: "健康的", example: "I try to stay healthy by walking every day.", prompt: "我每天散步来保持健康。" },
      { word: "exercise", meaning: "锻炼，运动", example: "I exercise three times a week.", prompt: "我每周锻炼三次。" },
      { word: "rest", meaning: "休息", example: "You need to rest after work.", prompt: "下班后你需要休息。" },
      { word: "balanced", meaning: "均衡的", example: "A balanced diet is important.", prompt: "均衡的饮食很重要。" },
      { word: "energy", meaning: "精力，能量", example: "I have more energy in the morning.", prompt: "我早上精力更充沛。" },
      { word: "stress", meaning: "压力，紧张", example: "Work can cause a lot of stress.", prompt: "工作会带来很多压力。" },
      { word: "mental", meaning: "心理的，精神的", example: "Mental health is as important as physical health.", prompt: "心理健康和身体健康同样重要。" },
      { word: "physical", meaning: "身体的，体力的", example: "Physical activity keeps you fit.", prompt: "体育活动让你保持健康。" },
      { word: "nutrition", meaning: "营养", example: "Good nutrition helps you stay well.", prompt: "良好的营养有助于保持健康。" },
      { word: "breathe", meaning: "呼吸", example: "Take a deep breath to calm down.", prompt: "深呼吸来平静下来。" },
      { word: "mood", meaning: "心情，情绪", example: "Exercise improves my mood.", prompt: "锻炼改善了我的心情。" },
      { word: "active", meaning: "积极的，活跃的", example: "Try to stay active during the day.", prompt: "尽量在白天保持活跃。" },
      { word: "pain", meaning: "疼痛", example: "I have a little pain in my back.", prompt: "我背部有点疼。" },
      { word: "recover", meaning: "恢复，康复", example: "It takes time to recover from a cold.", prompt: "从感冒中恢复需要时间。" },
      { word: "medicine", meaning: "药，医学", example: "The doctor gave me some medicine.", prompt: "医生给了我一些药。" },
      { word: "sleep", meaning: "睡眠，睡觉", example: "I need at least seven hours of sleep.", prompt: "我至少需要七小时睡眠。" },
      { word: "wellness", meaning: "健康，幸福", example: "Wellness includes both body and mind.", prompt: "健康包括身体和心灵。" },
      { word: "symptom", meaning: "症状", example: "A headache can be a symptom of stress.", prompt: "头痛可能是压力的症状。" },
      { word: "routine", meaning: "日常习惯，惯例", example: "I have a morning routine that keeps me healthy.", prompt: "我有保持健康的晨间习惯。" },
      { word: "hydrated", meaning: "补充水分的", example: "Drink water to stay hydrated.", prompt: "多喝水以保持水分。" },
    ],
    speaking: {
      title: "聊聊健康习惯",
      opener: "Let's talk about health today. How do you stay healthy in your daily life?",
      goal: "用英文描述你的健康习惯，并解释为什么这样做。",
    },
    writingLesson: {
      grammar: "I try to... 表达努力习惯",
      tip: "I try to... 用来表示你努力去做某件事。后面接动词原形：I try to sleep early.",
      examples: ["I try to exercise every morning.", "I try to eat less sugar."],
      prompts: [
        { zh: "我努力每天早睡。", answer: "I try to sleep early every day." },
        { zh: "我努力减少压力。", answer: "I try to reduce stress." },
        { zh: "我努力多喝水。", answer: "I try to drink more water." },
        { zh: "我努力每周锻炼三次。", answer: "I try to exercise three times a week." },
        { zh: "我努力保持积极的心态。", answer: "I try to stay positive." },
      ],
    },
  },
  {
    id: "travel-adventure",
    title: "旅行出行：探索世界",
    domain: "旅行",
    description: "练习旅行场景中的订票、问路、入住和沟通表达。",
    vocabulary: [
      { word: "trip", meaning: "旅行，出行", example: "I am planning a trip to Beijing.", prompt: "我正在计划去北京旅行。" },
      { word: "ticket", meaning: "票，车票，机票", example: "I need to buy a train ticket.", prompt: "我需要买一张火车票。" },
      { word: "passport", meaning: "护照", example: "Don't forget your passport.", prompt: "别忘了带护照。" },
      { word: "hotel", meaning: "酒店", example: "I booked a hotel near the station.", prompt: "我在车站附近订了一家酒店。" },
      { word: "airport", meaning: "机场", example: "We need to arrive at the airport early.", prompt: "我们需要早点到机场。" },
      { word: "luggage", meaning: "行李", example: "I only brought one piece of luggage.", prompt: "我只带了一件行李。" },
      { word: "direction", meaning: "方向，指引", example: "Can you give me directions to the station?", prompt: "你能告诉我去车站的方向吗？" },
      { word: "tourist", meaning: "游客，旅游者", example: "The city is full of tourists in summer.", prompt: "夏天这座城市到处都是游客。" },
      { word: "destination", meaning: "目的地", example: "Our destination is the old town.", prompt: "我们的目的地是古城。" },
      { word: "sightseeing", meaning: "观光，游览", example: "I love sightseeing in new cities.", prompt: "我喜欢在新城市观光。" },
      { word: "local", meaning: "当地的，本地人", example: "Ask a local for the best restaurants.", prompt: "向当地人打听最好的餐厅。" },
      { word: "transfer", meaning: "换乘，转机", example: "I have a two-hour transfer in Shanghai.", prompt: "我在上海有两小时转机。" },
      { word: "check in", meaning: "办理入住，值机", example: "We can check in after three o'clock.", prompt: "我们可以三点后办理入住。" },
      { word: "delay", meaning: "延误，推迟", example: "The flight has a two-hour delay.", prompt: "航班延误两小时。" },
      { word: "booking", meaning: "预订", example: "I made a booking online.", prompt: "我在网上做了预订。" },
      { word: "scenery", meaning: "风景，景色", example: "The mountain scenery is beautiful.", prompt: "山上的风景很美。" },
      { word: "adventure", meaning: "冒险，探险", example: "Travelling is a great adventure.", prompt: "旅行是一次很棒的冒险。" },
      { word: "culture", meaning: "文化", example: "I enjoy learning about local culture.", prompt: "我喜欢了解当地文化。" },
      { word: "souvenir", meaning: "纪念品", example: "I bought a souvenir for my friend.", prompt: "我给朋友买了一件纪念品。" },
      { word: "itinerary", meaning: "行程，日程表", example: "I have a busy itinerary this week.", prompt: "我这周的行程很满。" },
    ],
    speaking: {
      title: "计划一次旅行",
      opener: "Let's talk about travel today. Have you ever traveled somewhere interesting? Where would you like to go?",
      goal: "用英文介绍你的旅行计划或旅行经历，包含地点、安排和感受。",
    },
    writingLesson: {
      grammar: "I would like to... 礼貌表达愿望",
      tip: "I would like to... 是礼貌地表达想做某事，常用于旅行和服务场景。后接动词原形。",
      examples: ["I would like to visit Japan one day.", "I would like to book a room for two nights."],
      prompts: [
        { zh: "我想订一间两晚的房间。", answer: "I would like to book a room for two nights." },
        { zh: "我想要一张靠窗的座位。", answer: "I would like a window seat." },
        { zh: "我想了解一下当地的景点。", answer: "I would like to know about local attractions." },
        { zh: "我想早点入住，可以吗？", answer: "I would like to check in early, if possible." },
        { zh: "我想预订一辆出租车去机场。", answer: "I would like to book a taxi to the airport." },
      ],
    },
  },
  {
    id: "shopping-consumer",
    title: "购物消费：聪明选择",
    domain: "购物",
    description: "练习购物场景中询价、比较、付款和退换货的英语表达。",
    vocabulary: [
      { word: "price", meaning: "价格，价钱", example: "What is the price of this jacket?", prompt: "这件夹克的价格是多少？" },
      { word: "discount", meaning: "折扣，优惠", example: "Is there a discount for members?", prompt: "会员有折扣吗？" },
      { word: "afford", meaning: "负担得起", example: "I cannot afford this right now.", prompt: "我现在负担不起这个。" },
      { word: "compare", meaning: "比较", example: "Let me compare the two options.", prompt: "让我比较一下这两个选项。" },
      { word: "quality", meaning: "质量，品质", example: "The quality of this product is excellent.", prompt: "这件产品的质量很好。" },
      { word: "refund", meaning: "退款，退款", example: "I would like a refund for this item.", prompt: "我想退这件商品的款。" },
      { word: "exchange", meaning: "交换，换货", example: "Can I exchange this for a different size?", prompt: "我能换一个不同尺码吗？" },
      { word: "receipt", meaning: "收据，发票", example: "Please keep your receipt.", prompt: "请保留你的收据。" },
      { word: "brand", meaning: "品牌", example: "I prefer local brands.", prompt: "我更喜欢本地品牌。" },
      { word: "size", meaning: "尺码，大小", example: "Do you have this in a larger size?", prompt: "这个有更大的尺码吗？" },
      { word: "fitting room", meaning: "试衣间", example: "Where is the fitting room?", prompt: "试衣间在哪里？" },
      { word: "cash", meaning: "现金", example: "Do you accept cash?", prompt: "你们接受现金吗？" },
      { word: "online", meaning: "在线的，网上的", example: "I usually shop online.", prompt: "我通常网上购物。" },
      { word: "delivery", meaning: "配送，快递", example: "Free delivery for orders over one hundred.", prompt: "订单满一百免费配送。" },
      { word: "sale", meaning: "促销，特卖", example: "Everything is on sale this week.", prompt: "本周所有商品都在促销。" },
      { word: "expensive", meaning: "昂贵的", example: "This bag is too expensive for me.", prompt: "这个包对我来说太贵了。" },
      { word: "value", meaning: "价值，划算", example: "This is good value for the money.", prompt: "这个很划算。" },
      { word: "recommend", meaning: "推荐", example: "Can you recommend a good brand?", prompt: "你能推荐一个好品牌吗？" },
      { word: "popular", meaning: "受欢迎的，流行的", example: "This model is very popular.", prompt: "这款很受欢迎。" },
      { word: "checkout", meaning: "结账，收银台", example: "I am ready to checkout.", prompt: "我准备好结账了。" },
    ],
    speaking: {
      title: "购物对话",
      opener: "Let's practice shopping conversations. Imagine you are in a store. What do you usually look for when you shop?",
      goal: "用英文描述购物经历，学会询价、比较和表达偏好。",
    },
    writingLesson: {
      grammar: "Is there... / Are there... 询问是否有",
      tip: "购物时用 Is there...（单数）或 Are there...（复数）询问是否有某物。回答：Yes, there is. / No, there isn't.",
      examples: ["Is there a fitting room nearby?", "Are there any discounts today?"],
      prompts: [
        { zh: "附近有试衣间吗？", answer: "Is there a fitting room nearby?" },
        { zh: "今天有折扣吗？", answer: "Are there any discounts today?" },
        { zh: "有更小的尺码吗？", answer: "Is there a smaller size?" },
        { zh: "有其他颜色吗？", answer: "Are there other colors?" },
        { zh: "有会员卡优惠吗？", answer: "Is there a discount for members?" },
      ],
    },
  },
  {
    id: "family-relationships",
    title: "家庭关系：温暖联结",
    domain: "家庭",
    description: "用英语描述家庭成员、家庭活动和表达对家人的关心。",
    vocabulary: [
      { word: "family", meaning: "家庭，家人", example: "My family is very important to me.", prompt: "家庭对我非常重要。" },
      { word: "parent", meaning: "父母（之一）", example: "My parents live in another city.", prompt: "我父母住在另一个城市。" },
      { word: "sibling", meaning: "兄弟姐妹", example: "I have one older sibling.", prompt: "我有一个哥哥/姐姐。" },
      { word: "relationship", meaning: "关系", example: "A good relationship takes effort.", prompt: "良好的关系需要努力。" },
      { word: "support", meaning: "支持，帮助", example: "My family always supports me.", prompt: "我的家人一直支持我。" },
      { word: "responsibility", meaning: "责任", example: "Taking care of family is a big responsibility.", prompt: "照顾家人是一项重大责任。" },
      { word: "gather", meaning: "聚集，聚会", example: "We gather for dinner every Sunday.", prompt: "我们每个周日聚在一起吃饭。" },
      { word: "tradition", meaning: "传统", example: "It is a family tradition to cook together.", prompt: "一起做饭是一个家庭传统。" },
      { word: "memories", meaning: "记忆，回忆", example: "We have many happy memories together.", prompt: "我们有很多快乐的共同回忆。" },
      { word: "appreciate", meaning: "感激，欣赏", example: "I appreciate everything my parents do.", prompt: "我感激父母做的一切。" },
      { word: "argue", meaning: "争论，吵架", example: "Siblings sometimes argue but still love each other.", prompt: "兄弟姐妹有时会争论，但仍然相爱。" },
      { word: "celebrate", meaning: "庆祝", example: "We celebrate birthdays together.", prompt: "我们一起庆祝生日。" },
      { word: "proud", meaning: "自豪的，骄傲的", example: "My parents are proud of me.", prompt: "我的父母为我感到骄傲。" },
      { word: "care", meaning: "关心，照顾", example: "I care about my family deeply.", prompt: "我深深关心我的家人。" },
      { word: "grow up", meaning: "成长，长大", example: "I grew up in a small town.", prompt: "我在一个小镇长大。" },
      { word: "miss", meaning: "想念，思念", example: "I miss my family when I travel.", prompt: "旅行时我很想念我的家人。" },
      { word: "visit", meaning: "拜访，探访", example: "I visit my grandparents every holiday.", prompt: "每逢节假日我都去看望祖父母。" },
      { word: "trust", meaning: "信任", example: "Trust is the foundation of every family.", prompt: "信任是每个家庭的基础。" },
      { word: "together", meaning: "一起，共同", example: "We do everything together.", prompt: "我们一起做所有事情。" },
      { word: "generation", meaning: "代，一代人", example: "Three generations live in our house.", prompt: "我们家住着三代人。" },
    ],
    speaking: {
      title: "聊聊你的家人",
      opener: "Today let's talk about family. Can you tell me a little about your family?",
      goal: "用英文介绍家庭成员，描述家庭活动和表达对家人的感情。",
    },
    writingLesson: {
      grammar: "My ... is/are ... 描述家庭成员",
      tip: "描述家庭成员时，用 My + 称谓 + is/are + 描述词或动词短语。注意单复数和动词形式。",
      examples: ["My parents are very supportive.", "My sister is a teacher in Beijing."],
      prompts: [
        { zh: "我的父母非常支持我。", answer: "My parents are very supportive." },
        { zh: "我的姐姐在北京是一名老师。", answer: "My sister is a teacher in Beijing." },
        { zh: "我的家人每周日一起吃饭。", answer: "My family eats together every Sunday." },
        { zh: "我的祖父母住在乡下。", answer: "My grandparents live in the countryside." },
        { zh: "我的弟弟正在读大学。", answer: "My younger brother is studying at university." },
      ],
    },
  },
];

export const starterReviewItems: Omit<ReviewItem, "id" | "createdAt" | "updatedAt" | "nextReviewAt">[] = [
  {
    area: "vocabulary",
    title: "available",
    prompt: "用 available 表达：你明天有空吗？",
    answer: "Are you available tomorrow?",
    note: "available 常用于询问时间是否方便。",
    errorCount: 1,
    confidence: 2,
    streak: 0,
    status: "learning",
  },
  {
    area: "speaking",
    title: "回答不要只说 yes/no",
    prompt: "别人问 What do you do after work? 请用完整句回答。",
    answer: "After work, I usually read or watch a short video.",
    note: "口语练习要尽量给一句补充信息，让对话继续。",
    errorCount: 1,
    confidence: 2,
    streak: 0,
    status: "learning",
  },
  {
    area: "writing",
    title: "want to + 动词原形",
    prompt: "翻译：我想练习英语写作。",
    answer: "I want to practice English writing.",
    note: "want 后面接 to do，不写 want practice。",
    errorCount: 1,
    confidence: 2,
    streak: 0,
    status: "learning",
  },
];

export const areaLabels: Record<SkillArea, string> = {
  vocabulary: "词汇",
  speaking: "口语",
  writing: "写作",
};
